import React,{useEffect}from'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route,Link,useLocation}from'react-router-dom';import{Scene}from'./scene';import'./styles.css';
const nav=[['/','Home'],['/intelligence','Intelligence'],['/store','Store'],['/about','About'],['/contact','Contact']];
function Shell({children}){const loc=useLocation();useEffect(()=>{document.title=loc.pathname==='/'?'LUMAROZ INDUSTRIES':'LUMAROZ — '+loc.pathname.slice(1).toUpperCase();window.scrollTo(0,0)},[loc.pathname]);return <><Scene/><header className="nav"><Link className="logo" to="/">LUMAROZ<span>®</span></Link><nav>{nav.map(x=><Link key={x[0]} className={loc.pathname===x[0]?'active':''} to={x[0]}>{x[1]}</Link>)}</nav><Link className="nav-cta" to="/contact">LET'S BUILD ↗</Link></header><main>{children}</main><footer><Link className="logo" to="/">LUMAROZ<span>®</span></Link><span>INTELLIGENCE / SOFTWARE / OBJECTS</span><span>© 2026 LUMAROZ INDUSTRIES PVT. LTD.</span></footer></>}
const K=({children})=><div className="kicker"><i/>{children}</div>;
function Home(){return <><section className="hero section"><K>Independent technology company / India → world</K><h1>WE BUILD<br/><em>WHAT'S</em><br/>NEXT<span>.</span></h1><div className="hero-bottom"><p>Lumaroz Industries builds intelligent software and physical technology with one ambition: make the future feel usable.</p><span>SCROLL ↓</span></div></section><section className="section manifesto"><div className="index">01 / THE COMPANY</div><h2>A TECHNOLOGY<br/>COMPANY WITH<br/><b>A POINT OF VIEW.</b></h2><p>Not an agency. Not a collection of side projects. Lumaroz is a long-term technology company building products, systems and experiences across digital and physical space.</p></section><section className="section"><div className="index">02 / THE DIVISIONS</div><div className="division-grid"><Link to="/intelligence" className="division"><small>01 / INTELLIGENCE</small><strong>LUMAROZ<br/>INTELLIGENCE</strong><span>AI products, software and intelligent interfaces ↗</span></Link><Link to="/store" className="division"><small>02 / STORE</small><strong>LUMAROZ<br/>STORE</strong><span>Technology accessories and desk objects ↗</span></Link></div></section><section className="section statement"><K>Built patiently / shipped boldly</K><h2>THE FUTURE<br/><b>IS A PRODUCT.</b></h2><Link className="line-link" to="/about">DISCOVER LUMAROZ ↗</Link></section></>}
function Page({kicker,title,children}){return <section className="section inner"><K>{kicker}</K><h1>{title}</h1>{children}</section>}
function Intelligence(){return <Page kicker="01 / LUMAROZ INTELLIGENCE" title={<>INTELLIGENCE<br/><em>AS INFRASTRUCTURE.</em></>}><p className="lead">We build AI products and software that make computation feel closer to the person using it.</p><div className="feature-list"><Feature n="01" t="AI COMPANIONS" p="Context-aware assistants and interfaces designed around useful interaction."/><Feature n="02" t="AI TOOLS" p="Focused software that turns difficult workflows into simple actions."/><Feature n="03" t="DIGITAL EXPERIENCES" p="Websites and interfaces where technology becomes part of the experience."/><Feature n="04" t="R&D" p="Experimental work exploring new interaction models, automation and machine intelligence."/></div></Page>}
function Feature({n,t,p}){return <article className="feature"><span>{n}</span><h3>{t}</h3><p>{p}</p><b>↗</b></article>}
function Store(){return <Page kicker="02 / LUMAROZ STORE" title={<>TECHNOLOGY<br/><em>YOU CAN TOUCH.</em></>}><p className="lead">A physical extension of the Lumaroz system: useful objects for desks, creators and everyday computing.</p><div className="products"><Product n="01" t="KEYBOARD / 01" c="keyboard"/><Product n="02" t="MOUSE / 01" c="mouse"/><Product n="03" t="SPEAKER / 01" c="speaker"/></div></Page>}
function Product({n,t,c}){return <article className="product"><small>{n} / LUMAROZ STORE</small><div className={'product-shape '+c}/><h3>{t}</h3><span>IN DEVELOPMENT</span></article>}
function About(){return <Page kicker="03 / ABOUT LUMAROZ" title={<>BUILT FOR THE<br/><em>LONG TERM.</em></>}><p className="lead">Lumaroz Industries is an independent technology company. We operate where intelligence, software, design and physical technology meet.</p><div className="about-grid"><Block t="MAKE IT USEFUL." p="Technology should earn its place in someone's life."/><Block t="MAKE IT DISTINCT." p="We would rather build something memorable than something familiar."/><Block t="KEEP BUILDING." p="Lumaroz is designed as a company that compounds over years."/></div></Page>}
function Block({t,p}){return <div><span className="index">PRINCIPLE</span><h3>{t}</h3><p>{p}</p></div>}
function Contact(){return <Page kicker="04 / CONTACT" title={<>LET'S BUILD<br/><em>SOMETHING REAL.</em></>}><p className="lead">For partnerships, products, technology or simply a serious idea worth exploring.</p><a className="contact-email" href="mailto:hello@lumaroz.com">HELLO@LUMAROZ.COM ↗</a><div className="contact-meta"><span>INDIA / GLOBAL</span><span>LUMAROZ INDUSTRIES PVT. LTD.</span></div></Page>}
function App(){return <BrowserRouter><Shell><Routes><Route path="/" element={<Home/>}/><Route path="/intelligence" element={<Intelligence/>}/><Route path="/store" element={<Store/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/></Routes></Shell></BrowserRouter>}createRoot(document.getElementById('root')).render(<App/>);